name: Build, Push, and Deploy

on:
  push:
    branches:
      - main 

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    permissions:
      id-token: write 
      contents: read

    outputs:
      image_tag: ${{ steps.tag.outputs.tag }} 

    steps:
      - name: Checkout app repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: tag
        run: echo "tag=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build, tag, and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_URI }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.tag.outputs.tag }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ steps.tag.outputs.tag }}

update-config-repo:
  name: Update Helm Chart Values
  runs-on: ubuntu-latest
  needs: build-and-push
  permissions:
    contents: write 
    
  steps:
    - name: Install yq
      run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

    - name: Checkout config repo
      uses: actions/checkout@v3
      with:
        repository: VirginiaBensen/movie-project-config
        token: ${{ secrets.PAT_TOKEN }} 
        path: config-repo

    - name: Update values.yaml
      run: |
        export IMAGE_TAG=${{ needs.build-and-push.outputs.image_tag }}
        yq e -i '.image.tag = env(IMAGE_TAG)' config-repo/chart/values.yaml

    - name: Commit and push changes
      run: |
        cd config-repo
        git config --global user.name "GitHub Action Bot"
        git config --global user.email "action@github.com"
        git add chart/values.yaml
        git commit -m "Update image tag to ${{ needs.build-and-push.outputs.image_tag }}" || echo "No changes to commit"
        git push
